### ISSUE TITLE
Firmware not flashing, new serial number?

### ISSUE THREAD

**Issue by peely** [TheCrypt0/yi-hack-v4#109]
Hi all. I've just bought the "YI Cloud Dome Camera 1080P HD" (https://www.amazon.co.uk/gp/product/B07CTH3MBN). The serial number on the bottom starts with 8FUS, so i'm not sure its the same camera as any that are listed.

I tried putting an SD in with _h20 on, but it ignore them. I've seen [this Issue](https://github.com/TheCrypt0/yi-hack-v4/issues/49), but i'm not sure its for the same camera. Am I downloading the wrong firmware or have I got a new variant of this model of camera?

Any help appreciated, i'm just trying to get access to the cams video stream, so I can save it to my server instead of paying for the cloud ha. Thanks.

**Comment by DJBenson** [comment]
Subscribing to this thread on the basis I just ordered 2 of these cameras (same ASIN as above) from Amazon to hack.

**Comment by DJBenson** [comment]
Mine arrived from Amazon today with the 8FUS...serial, not tried flashing it yet but not overly hopeful.

**Comment by DJBenson** [comment]
As expected, the firmware is not read from the SD Card.

For reference, this is the model we are discussing, it appears to be a revised version based on the case.

![6598026F-B663-43D0-BBF5-BB16D4557F2B](https://user-images.githubusercontent.com/1013909/62330319-3cdef800-b4b0-11e9-9c40-e182d860855a.jpeg)

**Comment by jamieshaw** [comment]
I purchased this camera also (during the 33% reduction offer); same serial number of 8FUS; and the hack works like a charm – got it running with ZoneMinder and that feeding into Home Assistant without issue.

It's worth noting that the square bottomed model pictured above is the Yi _cloud_ dome, not the Yi dome – it requires **h19** opposed to h20.

**Comment by peely** [comment]
"Yi **_cloud_** dome"

I honestly hope I've been this stu... situationally unaware. Will try tonight.

**Comment by peely** [comment]
Yes, @jamieshaw you were right. I just didn't read 😞 Thank you for being nice in pointing out my mistake.

**Comment by jamieshaw** [comment]
No problem – these things happen, glad I could help 😄
