### ISSUE TITLE
Camhash changed

### ISSUE THREAD

**Issue by DJBenson** [TheCrypt0/yi-hack-v4#115]
So a very odd issue, I have two camera's (yi_cloud_dome_1080p and yi_dome_1080p). The latter I licensed last week with no issue, but the Cloud Dome camera has done something very strange.

The camhash has changed between me submitting the request and the license being generated. The camhash submitted was cached in Chrome so I could see that it was different and the confirmation sent was indeed for that hash.

This morning the hash is different which means the license will obviously not work.

Here's what was submitted versus the camhash this morning:
![image](https://user-images.githubusercontent.com/1013909/62763824-5d94e800-ba84-11e9-8452-66e7f525045b.png)

As I said, I have only two camera's, the other is licensed:
![image](https://user-images.githubusercontent.com/1013909/62763897-8a48ff80-ba84-11e9-86ef-7dcb47d1a3f7.png)

The only things which I did to the camera after requesting the license was;

- Change the camera name
- Assign the camera a static IP in my DHCP server
- Switch from the wireless connection to the ethernet connection

The latter is something which just came to me; surely you aren't generating the license based on the WLAN MAC address (which of course will be different depending upon which connection is being used)? The fact that when the camera is on LAN instead of WLAN that the MAC address is shown as below suggests you might be;

![image](https://user-images.githubusercontent.com/1013909/62764145-1824ea80-ba85-11e9-9f13-73a43c2fd354.png)

**Comment by TheCrypt0** [comment]
@DJBenson 
That's weird, the MAC address shouldn't change upon switching connection.

Send me a PM on Discord and we'll handle the issue.
