### ISSUE TITLE
Include DONATION ONLY to RTSP description

### ISSUE THREAD

**Issue by untotren** [TheCrypt0/yi-hack-v4#133]
For full transparency to users it should include in the RTSP description that it is by donation only.  It is a fact that should not be hidden.  My previous issue mentioning this was deleted, if it happens again I will be contacting Github directly.

**Comment by TheCrypt0** [comment]
Hi @untotren,
I agree with you, the point that the RTSP is available to the ones that have supported the project is written on the very second paragraph of the README.

For more clarity I've added the info to the "Features" list too. See: https://github.com/TheCrypt0/yi-hack-v4/commit/e70c38fa116a0eb5d5bf0c9b1eb016d8a0494ac0
