### ISSUE TITLE
does this guide work on yi-hack-v4

### ISSUE THREAD

**Issue by michael11123** [TheCrypt0/yi-hack-v4#148]
https://github.com/bobi/xiaomi_gdrive
please support me.
thankyou alot.

**Comment by michael11123** [comment]
@TheCrypt0  please help me.

**Comment by avengermsoft** [comment]
For the scripts to work, you need to add a <wc, stat, egrep, expr, basename, sort> to the BussyBox

**Comment by avengermsoft** [comment]
Ask @TheCrypt0 add modules to the next firmware release

**Comment by avengermsoft** [comment]
Add modules in pull request https://github.com/TheCrypt0/yi-hack-v4/pull/62

**Comment by michael11123** [comment]
> modu

so, i cant't use this guide yet?

**Comment by avengermsoft** [comment]
Try this mod [xiaomi_gdrive](https://github.com/avengermsoft/xiaomi_gdrive)

**Comment by michael11123** [comment]
> Try this mod [xiaomi_gdrive](https://github.com/avengermsoft/xiaomi_gdrive)

special thank you. 
and i will close this issue.

**Comment by michael11123** [comment]
![Capture](https://user-images.githubusercontent.com/46898583/67576036-fe33a380-f767-11e9-8d1b-435af9a5e2ab.PNG)
@avengermsoft 
so sad. 
I have successfully done it the first time.
but the second time it reported an error.

**Comment by michael11123** [comment]
so, i used FileZilla to put  "gdrive" to home/hd1 ( i creat new file hd1).
and then:
![Capture](https://user-images.githubusercontent.com/46898583/67613192-eb0aed00-f7d4-11e9-9f09-21ac31d1b935.PNG)

**Comment by michael11123** [comment]
i creat file /home/libusr and then
![2](https://user-images.githubusercontent.com/46898583/67613893-46d97400-f7dd-11e9-899c-5684db303365.PNG)

**Comment by michael11123** [comment]
> Try this mod [xiaomi_gdrive](https://github.com/avengermsoft/xiaomi_gdrive)

can this mod work on yi 1080 or dome?

**Comment by avengermsoft** [comment]
Where did you get the curl? My curl does not require libz.so.1. Tell me the size of the curl - 
`ls -al /home/hd1/gdrive/yi-hack-v4/bin`

**Comment by michael11123** [comment]
I have reinstalled by your mod and worked.

**Comment by michael11123** [comment]
i have the problem. time on record folder is not same on device.
i use GMT + 7.

**Comment by michael11123** [comment]
> Where did you get the curl? My curl does not require libz.so.1. Tell me the size of the curl -
> `ls -al /home/hd1/gdrive/yi-hack-v4/bin`
[curl.zip](https://github.com/TheCrypt0/yi-hack-v4/files/3775399/curl.zip)
curl file of porunov
