### ISSUE TITLE
Rebot the camera YI 1080 by command line

### ISSUE THREAD

**Issue by Booperly** [TheCrypt0/yi-hack-v4#177]
Is there a command line that allows you to reboot the camera without going through the YI-hack web page. Thank you

**Comment by TheCrypt0** [comment]
Hi @Booperly,
You can use `reboot` or `reboot -f` to force a reboot.

Or alternatively you can call this script https://github.com/TheCrypt0/yi-hack-v4/blob/master/src/www/httpd/cgi-bin/reboot.sh

Which is the same that gets called by the Reboot page.

**Comment by nelutzu777** [comment]
https://github.com/TheCrypt0/yi-hack-v4/issues/328#issuecomment-1293251809
