### ISSUE TITLE
Support for latest Yi Home Camera 3 (6FCN) model?

### ISSUE THREAD

**Issue by ShikyC** [TheCrypt0/yi-hack-v4#182]
Hi is there any plans for the latest Yi Home Camera 3 (6FCNXXXXX) model? I got very few information about this model though.

**Comment by empatel96** [comment]
[https://github.com/roleoroleo/yi-hack-MStar](url)

There's this one available

**Comment by ShikyC** [comment]
Wow this looks awesome! Thank you so much!!!
