### ISSUE TITLE
Stock firmware for yi home dome

### ISSUE THREAD

**Issue by AnDyC420** [TheCrypt0/yi-hack-v4#186]
The app.box link is dead can anyone share the stock firmware for a non cn version  yi home dome 720p camera

**Comment by idanny76** [comment]
Trying to go back to stock firmware, but I cant seem to figure it out. I have downloaded the stock firmware and placed in the sd card root. But after rebooting it has the Yi Hack V4 firmware.

**Comment by idanny76** [comment]
I figured it out. The stock firmware after it is downloaded it has be renamed to a specific name. PDF file here shows names of files depending on the camera version.

https://oss.yitechnology.com/images/support/homecam2usermanual.pdf

https://www2.yitechnology.com/firmware/index

**Comment by AnDyC420** [comment]
I have only just seen this thanks for the link
