### ISSUE TITLE
Installing after yi-hack-v3

### ISSUE THREAD

**Issue by Nixellion** [TheCrypt0/yi-hack-v4#19]
I currently have a 1080p Dome camera with yi hack v3 installed on it.

Are there any extra steps to install yi-hack-v4? Or should I just do the same as I would install it on a stock firmware?

**Comment by getutsav** [comment]
I never got it to work properly with an update from v3 to v4. I would recommend going back to stock firmware and then installing v4 from there.

**Comment by Nixellion** [comment]
Thanks!

**Comment by TheCrypt0** [comment]
@Nixellion 
Upgrading directly from yi-hack-v3 to v4 shouldn't cause any problem. But in rare cases where problems occur reverting to stock and then upgrade will work.

If you have any problem feel free to re-open the issue.
