### ISSUE TITLE
"The license you uploaded isn't for this camera."

### ISSUE THREAD

**Issue by peely** [TheCrypt0/yi-hack-v4#209]
Yes it is. It's been a long time since I turned the camera on, but I got sent the Licence on Aug 6, 2019, at 7:40 AM, and I did use it and it worked. I've now finally got round to setting the camera up, and the RTSP is reporting this issue. I've tried re-uploading the files. Whats the deal.

**Comment by TheCrypt0** [comment]
Hi @peely 
Sometimes the hardware IDs change after some time. Can you please send a mail with the info about the camera?

You can directly reply to the original mail with the license attached.

Let me know.
