### ISSUE TITLE
homeassistant yi cam connection

### ISSUE THREAD

**Issue by tnTano** [TheCrypt0/yi-hack-v4#21]
hi to all...
i have one yi 1080p dome and two yi 1080p outdoor camera.

I installed the yi-hack-v4 firmware but i can't connect them to home assistant.... 
here the code i've got on HA:
`- platform: yi
  name: Corridoio
  host: !secret camera_ip_01
  password: !secret camera_pwd
  path: !secret ftp_url'
###
- platform: yi
  name: Ingresso
  host: !secret camera_ip_02
  password: !secret camera_pwd
  path: !secret ftp_url'
###
- platform: yi
  name: Cortile
  host: !secret camera_ip_03
  password: !secret camera_pwd
  path: !secret ftp_url`

the entities created succesfully but if i put it on the dashboard the entity are inactive

how can i resolve this problem?

thanks

**Comment by Letherwin** [comment]
This is the configuration for my 1080p dome:

camera:
  - platform: ffmpeg
    name: Yi-Dome-1
    input: -an -i rtsp://192.168.1.250/ch0_0.h264

**Comment by tnTano** [comment]
ok, is it working without using the YI component??

i'll try it...

thanks

**Comment by TheCrypt0** [comment]
Hi @tnTano 
See this guide on how to configure the camera on Home Assistant: https://github.com/TheCrypt0/yi-hack-v4/wiki/Home-Assistant-configuration

Feel free to re-open if you have further issues.

**Comment by mitchross** [comment]
The wiki does not work.

**Comment by codeclinic** [comment]
@TheCrypt0 The link you provided above just point to a blank page editor. Any chance of it being restored? Thanks.

**Comment by TheCrypt0** [comment]
@mitchross @codeclinic 

Someone must have edited the page. Fixed!
