### ISSUE TITLE
Blue led light

### ISSUE THREAD

**Issue by SxS46** [TheCrypt0/yi-hack-v4#210]
Is possible to add the option to shutdown the blue led light? I've other xiaomi cameras with custom firmware and is possible there.
Thank you

**Comment by TheCrypt0** [comment]
Hi,
This is already possible from the app. If you have the Cloud features
disabled you have to enable them to disable the led and then you can
re-disable the Cloud features.

Cheers

**Comment by SxS46** [comment]
Not very straightforward but working.
Thank you
