### ISSUE TITLE
Disable stock firmware features

### ISSUE THREAD

**Issue by laurensk** [TheCrypt0/yi-hack-v4#242]
Is it possible to disable the stock firmware features so that I can make sure that the camera doesn't send any data to external servers and so on?

Thanks!

**Comment by TheCrypt0** [comment]
Hi, this is already implemented in the firmware. Please take a look at the
README, particularly to the "Disable Cloud" feature.

>

**Comment by laurensk** [comment]
Very nice! So when I disable all could features and restrict the internet access for the camera on my firewall, nothing bad should happen!!

Love this! Thank you!!
