### ISSUE TITLE
It is impossible to flash the Yi Home 1080p Camera

### ISSUE THREAD

**Issue by Dragon0501** [TheCrypt0/yi-hack-v4#248]
I copied the files to the root directory of the SD card. After this I inserted the SD and cut the AC. After reconnecting it starts normal the original firmware. No flashing or other... Pleas help me! I am using a 32gb card. Will it work or do I have to buy a smaller one? How can I find out which chipset I have or which firmware I have to use?

**Comment by jflemieux** [comment]
If your firmware version is 8.2.0, use this version : https://github.com/roleoroleo/yi-hack-Allwinner

**Comment by Dragon0501** [comment]
Which version do I have to use? 
![IMG_20200702_154600](https://user-images.githubusercontent.com/59663011/86366798-8402d980-bc7b-11ea-8577-2c25305ed23d.jpg)

**Comment by jflemieux** [comment]
Your version is the same I had before flashing. Follow the instructions on the repo I previously linked to ( I used the y20gam_0.1.6.tgz file )

**Comment by Dragon0501** [comment]
Will give it a try! Thank you!

**Comment by Dragon0501** [comment]
thank you very much! worked without a problem!!!
