### ISSUE TITLE
Safe to delete files after hack?

### ISSUE THREAD

**Issue by silly-questions** [TheCrypt0/yi-hack-v4#28]
Hello, just a quick silly question.  After flashing the home camera is it ok to delete the two files rootfs and home from the sd card?  Fantatsic work by the way to all involved, managed to flash my 3 cameras without an issue and now want to look into RTSP to try and set up someway to record the files locally.

**Comment by nicmorais** [comment]
Yes, it's safe to delete them.

**Comment by TheCrypt0** [comment]
I confirm what @nicmorais said. The files are safe to delete once they have been flashed.

Closing
