### ISSUE TITLE
RTSP Audio

### ISSUE THREAD

**Issue by 1onar** [TheCrypt0/yi-hack-v4#283]
I just activated/bought my License for RTSP but there is no audio. There is only the option for the second aac-stream.
Is there a way to merge them? I wanted to use my Synology Surveillance Station and need the audio.

**Comment by TheCrypt0** [comment]
Hi @1onar ,
Unfortunately this is not possible yet.

I'll re-open the issue and mark it as solved I'll manage to make it work in the future!
