### ISSUE TITLE
Is this project already dead?

### ISSUE THREAD

**Issue by alienatedsec** [TheCrypt0/yi-hack-v4#308]
There are no updates since last year (May 2019), and other similar projects have their updates regularly. Unfortunately, it is all related to the type of chipset; however, this project promised ONVIF from day one, and I genuinely supported it with my two cameras and wanted to follow with the rest. I realised in time before throwing my money into the hole.

There is no need to mention the support and earlier issues have no response and have no progress with anything.

I am sure the licensing portal and their system are working perfectly, so the money collection is the only thing you can expect from this project.

**Comment by Rushmed** [comment]
I am interested too.

**Comment by influenist** [comment]
v5 anyone ... ? :-)

**Comment by ljmerza** [comment]
he [responds](https://github.com/TheCrypt0/yi-hack-v4/issues/212) when it comes to someone donating money but for this? nah. project has been dead since may.

**Comment by swayer89** [comment]
I am interested too.

**Comment by jdieztec** [comment]
Really fast to answer to receive payments, no answer on any issue.

I think that if you have abandoned this you should have the decency to warn the new users before throwing their money on a dead project.

**Comment by alienatedsec** [comment]
Please see my fork - there is still work to do on space and other areas, but it is in progress

**Comment by TheCrypt0** [comment]
@alienatedsec Would you mind dropping me a pm on discord or a mail? I tried to find you on the server but without much luck.

Lately I've been testing some other forks with PTZ functionality and stuff and, if you are willing to, I'm sure we can join our forces to include a lot of fixes, features. I'll be more than happy to give you a jumpstart.

Let me know,
Crypto

**Comment by alienatedsec** [comment]
@TheCrypt0 

![image](https://user-images.githubusercontent.com/73167064/108899939-eea0c500-7610-11eb-9b4f-e2458cac11b6.png)

**Comment by alienatedsec** [comment]
> Lately I've been testing some other forks with PTZ functionality and stuff and, if you are willing to, I'm sure we can join our forces to include a lot of fixes, features. I'll be more than happy to give you a jumpstart.

@TheCrypt0 As much as your message had good intentions, and despite I have contacted you via Discord, it would be useful to continue our conversation and see how you want to contribute further.

Unfortunately, your RTSP donation system you created around your repository is no longer valid in my fork. This will mean that we could work together and 'join our forces' as you said, or we will explore our developments separate from each other.

I am happy to work either way.

**Comment by joseantgv** [comment]
> @TheCrypt0
> 
> ![image](https://user-images.githubusercontent.com/73167064/108899939-eea0c500-7610-11eb-9b4f-e2458cac11b6.png)

How can I join the Discord server? Thanks.
