### ISSUE TITLE
Internet Connection needed?

### ISSUE THREAD

**Issue by Elfearo** [TheCrypt0/yi-hack-v4#31]
Hi there,

i just successfully flashed a 1080p home camera with your firmware. But either i got something wrong, or i made a misstake in my configuration.

The camera is in my Wlan and i wanted to use the Yi Home App, to use it. But i wanted to get rid of the Cloud Features. So i flashed it and disabled internet connection for the camera in my Router.

But now i dont get any connect to the camera anymore. I testet a lot, and both things ( a - Disabling Internet in the Firewall / b - Disabling Cloud features )  will make my camera not work with the app anymore.

Is there any other way / app i must use, after disabling the online connection of the camera? The way it is right now it is kind of useless for me, unless i want to ignore the fact of security. RSTP doesnt seem to fully work yet, and i would loose the features of the app...

Last interesting fact i found out: If i disable the online connection in the firewall, after i first started the camera, the app will keep on working. But after every restart of the camera, it needs to go online to work.

Thank you for your effort in building such a nice custom firmware, i hope i will get it working for me.

Bye
Michael

**Comment by TheCrypt0** [comment]
Hi @Elfearo 

The cloud features require internet connection to work. If you disable them the App won't work anymore.

Feel free to re-open if you have further issues.

Cheers
