### ISSUE TITLE
Bricked y20 1080p

### ISSUE THREAD

**Issue by bgroins** [TheCrypt0/yi-hack-v4#36]
I seemed to have bricked a Yi Home 1080P y20 after installing this. The lights flash as normal, and I was even able to flash the recovery image. However, when it powers up the orange light stays on for about 15 seconds, the camera makes an audible click sound, then goes dark. Anyone else have this issue before? I'm nervous about trying to flash more cameras.

**Comment by bgroins** [comment]
Fixed my own issue. I was using a 2 GB SD card, and switched to a 32 GB. Was able to flash the recovery image and I'm guessing the hack will work as well. You might want to change "preferably of capacity 16gb or less" on the instructions, because there seems to be an issue with cards that are too small.

**Comment by bgroins** [comment]
Verified... hack works fine with the larger card.

**Comment by bgroins** [comment]
OK I'm an idiot. I had my status light set to off.

**Comment by Vormillion** [comment]
HI @bgroins - may I know where did you buy this camera? I'm trying to buy compatible model but description is not clear at all.

**Comment by TheCrypt0** [comment]
@bgroins 
Great to know. If you have any other problems feel free to open an issue! 

Closing.
