### ISSUE TITLE
Question about SD card

### ISSUE THREAD

**Issue by kalety** [TheCrypt0/yi-hack-v4#38]
It's needed that the SD card remains in its slot after firmware modification?, or we can remove it, and the camera works without any SD in the slot?.

Thank you.

**Comment by TheCrypt0** [comment]
Hi kalety,
the SD card can be removed after the firmware installation.

Cheers

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kalety** [comment]
Thank you Crypt0!
