### ISSUE TITLE
Bootloop when playing with services

### ISSUE THREAD

**Issue by Elfearo** [TheCrypt0/yi-hack-v4#40]
Hi there,

i found an issue.

After enabling rtsp and viewd my camera went nuts. After playing around with services like ssh and ftp and enabling and disabling them via the menu, the camera went into a bootloop.  That means it went back to the "waiting to connect" start, and stays there in a kind of loop. Meaning i can scan a code, but when trying to get into any Wlan it will just blink a bit, and then reboot, asking for connection again.

Fix is possible by reverting to an old version and getting back up. 

Bye

**Comment by TheCrypt0** [comment]
@Elfearo 
Thanks for your reporting. I'll add a "How to Unbrick your camera" section.

Cheers
