### ISSUE TITLE
Yi Home Camera 2

### ISSUE THREAD

**Issue by berlingozzo** [TheCrypt0/yi-hack-v4#5]
Hi
Thanks a lot for your efforts! I know the Yi Home Camera 2 is based on a different chipset, but any chances you could work on that as well? I have some of them and would like to help if possible. The only hacks available are based on an outdated firmware.
Thank you!

**Comment by TheCrypt0** [comment]
Hi @berlingozzo,
I don't have much knowledge about that model of the camera.. for what I can read from https://github.com/shadow-1/yi-hack-v3/issues/38 it has a completely different architecture. 

Greetings
