### ISSUE TITLE
How to bypass "Can only be used in China" region lock?

### ISSUE THREAD

**Issue by fulwater** [TheCrypt0/yi-hack-v4#55]
Hi guys. I brought my camera back from China to Asia recently and I've been looking for a way to use it. v3 didnt work because of the dead proxy list. I am not tech inclined so I'm asking for a bit more simplified help if possible.

My unit is a 1080 Dome Camera (Black).

Regards

**Comment by nicmorais** [comment]
Take a look at [this issue](https://github.com/TheCrypt0/yi-hack-v4/issues/37)
From what I know, you must set Proxychains-ng and download the [chinese YI home app](https://github.com/shadow-1/yi-hack-v3#which-smartphone-app-to-use)
My camera is not chinese, so I don't know how to properly bypass the region lock...

**Comment by TheCrypt0** [comment]
Duplicate issue, please refer to the issue that @nicmorais linked.

Closing.
