### ISSUE TITLE
Question about WiFi chip models on the supported cameras

### ISSUE THREAD

**Issue by HappyZ** [TheCrypt0/yi-hack-v4#69]
Hi, sorry I cannot really find much info online, and I come here for a little bit help. I am looking for the WiFi chipset models (for example, BCM43143 or maybe something else) on each of the supported cameras, i.e.

Yi Home 17CN / 27US / 47US
Yi 1080p Home
Yi Dome
Yi 1080p Dome
Yi 1080p Cloud Dome
Yi 1080p Outdoor

Thanks a lot for the help!

**Comment by nicmorais** [comment]
Connect via SSH, run `lsusb` and Google the ID of the first device.
My 27US and 48US cameras have both a MT7601

**Comment by HappyZ** [comment]
thx! appreciated!
