### ISSUE TITLE
Home Assistant Wiki Article Does Not Work

### ISSUE THREAD

**Issue by mitchross** [TheCrypt0/yi-hack-v4#79]
Followed the guide here https://github.com/TheCrypt0/yi-hack-v4/wiki/Home-Assistant-RTSP-configuration.

![Screen Shot 2019-06-09 at 1 32 16 PM](https://user-images.githubusercontent.com/6330506/59162210-312c1200-8abb-11e9-9927-5b7f315f9b73.png)
![Screen Shot 2019-06-09 at 1 32 01 PM](https://user-images.githubusercontent.com/6330506/59162212-34270280-8abb-11e9-8124-23bf1d46d3f8.png)
<img width="478" alt="Screen Shot 2019-06-10 at 9 07 44 PM" src="https://user-images.githubusercontent.com/6330506/59236375-ddf1b680-8bc3-11e9-90ca-e9867bda2981.png">
<img width="468" alt="Screen Shot 2019-06-10 at 9 04 51 PM" src="https://user-images.githubusercontent.com/6330506/59236381-e21dd400-8bc3-11e9-84d8-9324dccb0da3.png">

**Comment by lance36** [comment]
to me it looks like something is wrong with your home-assistant installation, care to share some details on how is it installed?

can you also check the homea-assistant logfile? it could be either the ffmpeg or the stream component are not getting initialized correctly.
do you get a still image but no live-feed?

**Comment by mitchross** [comment]
I used a raspberry pi 3 + this install  sudo curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | sudo bash -s -- -m raspberrypi3


These are two issues I see

https://github.com/home-assistant/home-assistant/issues/22840
https://github.com/home-assistant/home-assistant/issues/23561
