### ISSUE TITLE
Add OSD in camera view

### ISSUE THREAD

**Issue by jokerigno** [TheCrypt0/yi-hack-v4#83]
HI,

I just flashed with your firmware 2 outdoor yi camera. Everything is working as expected but I was wondering if you can add OSD functionality in order to be "sure" that the streaming is going.

Thank you in advance

**Comment by TheCrypt0** [comment]
Hi @jokerigno,
unfortunately this is not possible because the H264 encoder is directly controlled by the Xiaomi services. Currently the best we can do is to change the watermark.

Cheers

**Comment by jokerigno** [comment]
Thank you for the feedback anyway.

Bye
