### ISSUE TITLE
Video is corrupted after install

### ISSUE THREAD

**Issue by lucaventurini** [TheCrypt0/yi-hack-v4#88]
Hi,

I noticed that after I installed the hack, most or all notification videos in the app have strange "artifacts". When a person walks in front of the camera, for example, all the path she walks by gets pixellated, like a shadow. I don't know if this is a known issue or a codec problem maybe. Before the hack the video was perfect.

**Comment by TheCrypt0** [comment]
Solved by removing the SD card. See: https://github.com/TheCrypt0/yi-hack-v4/issues/173#issuecomment-688673736
