### ISSUE TITLE
Yi Dome X Support 

### ISSUE THREAD

**Issue by iltruma** [TheCrypt0/yi-hack-v4#92]
When you can add firmware for yi dome X?
it's the new model of yi dome 1080p

Thanks

**Comment by f4t0** [comment]
hi. I need support for yi dome X too.
Thanks

**Comment by gtramt1** [comment]
Hi, i would like to know if Dome X is international version of this one https://www.xiaoyi.com/homeCamera/homeCamera_h7/index.html

I have it and i can only use it via chinese VPN which are not reliable - flashing international firmware would fix this problem?

**Comment by ykhandler** [comment]
@gtramt1, there are chinese version and also international version, the serial number begin *FCN in the bottom of the camera is chinese version *FUS is international version.
No, flashing international firmware wont fix the problem, the serial is checked on the camera and  server side to determine chinese or international version.

**Comment by stream74** [comment]
HI, yes is it possible to have it for yi Dome X

**Comment by fintmu** [comment]
I have Yi Dome X camera also and would very much like to add it to my Home Assistant environment. Any firmware coming soon for it? If any help needed for testing etc. please ask.

**Comment by skeltonmfc** [comment]
So This hack doesn't work with the Dome X ?

**Comment by fintmu** [comment]
As far as I know the answer is no. It's not a supported model. I have this camera and it's totally useless for me because I can not connect it to my Home Assistant environment.

**Comment by skeltonmfc** [comment]
I would be happy to donate some money if we can get this going ?

**Comment by Kugelfang666** [comment]
I would also be greatly interested in a solution for this model

**Comment by pumabaer** [comment]
I would also be happy if this model is supported:)

**Comment by davimas** [comment]
Hey, and now one year later - how is the status?

**Comment by ma-karai** [comment]
any hope"?

**Comment by skeltonmfc** [comment]
would really love this 2 !!!!!

**Comment by winstarshl** [comment]
Any news for this cam?

**Comment by fabertel** [comment]
me too interested .. what happens if we try to flash it anyway ? do we break it ?

**Comment by antodeilippo** [comment]
I'm strongly interested, is there some way to hack to dome X and add it to home assistant ?

**Comment by iltruma** [comment]
@antodeilippo Try the firmware of repository https://github.com/roleoroleo/yi-hack-MStar

**Comment by iltruma** [comment]
Repository no longer mantaied for Yi Dome X
