### ISSUE TITLE
Find out camera version

### ISSUE THREAD

**Issue by l4ci** [TheCrypt0/yi-hack-v4#99]
Hey guys,

I am having trouble installing the yi-hack.

I wonder if it has to do with the quite new cameras (https://de.aliexpress.com/item/32818420214.html?spm=a2g0s.9042311.0.0.4df24c4d17VFgF).

Is this supported?

How do you even read out the correct version of the camera? I dont see it anywhere any you guys seem to read more ... like "24US, 5FCN ..." (https://github.com/TheCrypt0/yi-hack-v4/issues/74)

This is what I can read from the `diagnosis.txt` on the SD Card:

```
>>> Device Diagnosis <<<
+ cat /etc/os-release
NAME=Buildroot
VERSION=2017.08-gb77618e
ID=buildroot
VERSION_ID=2017.08
PRETTY_NAME="Buildroot 2017.08"
MODEL_COMMIT=7f43c64
COMMON_COMMIT=b77618e
XIAOMI_VERSION=3.5.1_0066
XIAOMI_BUILDNO=85  
#Build in Mon Apr 15 04:58:33 UTC 2019/ 64bf91150a4e by jenkins
```

I tried flashing `yi_home_1080p` and `yi_home` - both dont seem to flash anything. Cam led turns quickly blue. Even after resetting everything and trying again.

![back of the case](https://i.imgur.com/CTm1eNO.jpg)
![back of the cam](https://i.imgur.com/17NGDG9.jpg)

**Comment by edofullin** [comment]
Scan the qr code at the back of the camera, the first 4 chars represent the model. 
Yours is 04CF which, as you can see [here](https://github.com/TheCrypt0/yi-hack-v4/wiki/Supported-Camera-Models), is not supported

**Comment by l4ci** [comment]
Alright thanks!
